# Auto-generated by qt-pods. Do not edit.
# Include this to your application project file with:
# include(../pods.pri)
# This file should be put under version control.

INCLUDEPATH += \
	../qtwebserver 

LIBS += \
	-L../qtwebserver -lqtwebserver 

include(qtwebserver/qtwebserver.pri)

