# Auto-generated by qt-pods.
# This file should be put under version control.
TEMPLATE = subdirs
SUBDIRS = \
    minimal \
    dommanipulation \
    database \
    https \
    dataurl

include(pods-subdirs.pri)

OTHER_FILES = \
    LICENSE \
    README.md
